=== robbyn/messages/src/main/resources/org/tastefuljava/messages/xml/messages.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT messages (description?,definition*,message*)>
<!ATTLIST messages
    prefix CDATA #IMPLIED
    default-language CDATA #IMPLIED
>

<!ELEMENT description (#PCDATA)>

<!ELEMENT definition (#PCDATA)>
<!ATTLIST definition
    name CDATA #REQUIRED
    value CDATA #IMPLIED
>

<!ELEMENT message (description?,text+)>
<!ATTLIST message
    name CDATA #REQUIRED
    parameters CDATA #IMPLIED
>

<!ELEMENT text (#PCDATA|out|if|select|list)*>
<!ATTLIST text
    language CDATA #REQUIRED
>

<!ELEMENT if (#PCDATA|out|if|select|list)*>
<!ATTLIST if
    condition CDATA #REQUIRED
>

<!ELEMENT select (when+,otherwise?)>

<!ELEMENT when (#PCDATA|out|if|select|list)*>
<!ATTLIST when
    condition CDATA #REQUIRED
>

<!ELEMENT otherwise (#PCDATA|out|if|select|list)*>

<!ELEMENT out EMPTY>
<!ATTLIST out
    value CDATA #REQUIRED
>

<!ELEMENT list (#PCDATA|out|if|select|list)*>
<!ATTLIST list
    value CDATA #REQUIRED
    variable CDATA #REQUIRED
    separator CDATA #IMPLIED
>

=== robbyn/messages/src/test/resources/org/tastefuljava/messages/xml/messages.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE messages
    PUBLIC '-//tastefuljava.org//Message File 1.0//EN' 'messages.dtd'>
<messages default-language="en">
    <message name="appNotFound" parameters="app">
        <text language="en">
            Unknown application: <out value="app"/>.
        </text>
    </message>
    <message name="select" parameters="a,b">
        <text language="en">
            (<select>
                <when condition="a==0">
                    zero
                    <select>
                        <when condition="b==0">
                            zero
                        </when>
                        <when condition="b==1">
                            one
                        </when>
                        <when condition="b==2">
                            two
                        </when>
                        <when condition="b==3">
                            three
                        </when>
                        <otherwise>
                            something else
                        </otherwise>
                    </select>
                </when>
                <when condition="a==1">
                    one
                </when>
                <when condition="a==2">
                    two
                </when>
                <when condition="a==3">
                    three
                </when>
                <otherwise>
                    something else
                </otherwise>
            </select>)
        </text>
    </message>
</messages>
